version: '3.8'

services:
  mongo1:
    container_name: mongo1
    image: mongo
    volumes:
      - ./scripts/rs-init.sh:/scripts/rs-init.sh
      - ./scripts/init.js:/scripts/init.js
    networks:
      - mongo-network
    ports:
      - "27017:27017"
    depends_on:
      - mongo2
      - mongo3
    links:
      - mongo2
      - mongo3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongo2:
    container_name: mongo2
    image: mongo
    networks:
      - mongo-network
    ports:
      - "27018:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  mongo3:
    container_name: mongo3
    image: mongo
    networks:
      - mongo-network
    ports:
      - "27019:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongo-express:
    image: "mongo-express:latest"
    container_name: "mongo-express"
    ports:
      - "8088:8081"
    networks:
      - mongo-network
    links:
      - "mongo1"
    depends_on:
      - "mongo1"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo1:27017/?replicaSet=dbrs
      - ME_CONFIG_MONGODB_SERVER=mongo1
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      # - ME_CONFIG_OPTIONS_EDITORTHEME=night
      # - ME_CONFIG_REQUEST_SIZE=100kb
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    restart: always

networks:
  mongo-network:
    driver: bridge

#  localsqlserver:
#    image: mcr.microsoft.com/mssql/server:2022-latest
#    hostname: 'localsqlserver'
#    ports:
#      - "1433:1433"
#    environment:
#      - ACCEPT_EULA=Y
#      - MSSQL_SA_PASSWORD=SuperP4ssw0rd!
#      - MSSQL_PID=Developer
#    command:
#      - /bin/bash
#      - -c
#      - |
#        # Launch MSSQL and send to background
#        /opt/mssql/bin/sqlservr &
#        sleep 10
#        /opt/mssql-tools/bin/sqlcmd -U sa -P $$MSSQL_SA_PASSWORD -l 30 -e -Q "create database buyMeCoffee"
#        # So that the container doesn't shut down, sleep this thread
#        sleep infinity
#  sqlpad:
#    image: 'sqlpad/sqlpad:latest'
#    hostname: 'sqlpad'
#    ports:
#      - '3000:3000'
#    environment:
#      SQLPAD_ADMIN: 'mailto:admin@sqlpad.com'
#      SQLPAD_ADMIN_PASSWORD: 'admin'
#    volumes:
#      - sqlpad-volume:/var/lib/sqlpad
#
#volumes:
#  sqlpad-volume:
#
